<?php

CONST SITE_DIR = __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR;

CONST PUBLIC_DIR = SITE_DIR.'public'.DIRECTORY_SEPARATOR;

CONST IMG_DIR = PUBLIC_DIR.'img'.DIRECTORY_SEPARATOR;

CONST ENGINE_DIR = SITE_DIR.'engine'.DIRECTORY_SEPARATOR;

CONST CONFIG_DIR = SITE_DIR.'config'.DIRECTORY_SEPARATOR;


?>

